dist: bionic
services:
  - xvfb
addons:
  firefox: latest
  apt:
    packages:
      firefox-geckodriver
language: python
env:
  global:
  - PIP_RETRIES=10
  - PIP_TIMEOUT=30
#  - BROWSER=firefox
#  - GECKODRIVER=0.24.0
  - MOZ_HEADLESS=1
matrix:
  include:
  - python: 3.8
    env: TOXENV=checkqa
  - python: 3.8
    env: TOXENV=docs
  - python: 3.8
    env: TOXENV=py38-dj30
#  allow_failures:
#  - env: TOXENV=py38-dj30
install:
- travis_retry pip install -U pip
- travis_retry pip install tox
- travis_retry pip freeze
before_script:
- if echo "$TOXENV" | grep mysql; then mysql -e 'create database autocomplete_light_test;';
  fi
- if echo "$TOXENV" | grep postgresql; then psql -c 'create database autocomplete_light_test;'
  -U postgres; fi
script:
- tox -r
- test -d .tox/$TOXENV/log && cat .tox/$TOXENV/log/*.log || true
after_success:
- travis_retry pip install codecov
- cd test_project && codecov
notifications:
  irc:
    channels:
    - irc.freenode.org#yourlabs
    template:
    - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
cache:
  directories:
  - .tox/$TOXENV
  - $HOME/.cache/pip
